CALL create_account("ibcadmin", "$2a$10$VEflIDT1RYW0Tj47vb5D..ZCKGT0oOVsc0y2xS6O9MHKew/oeZXrS", "belamidemills29@gmail.com", "ibc", "admin", "Peter Parker (Fake name)");
CALL create_account("jetadmin", "$2a$10$5qQUIOUsc4VMz23/pdB1AOKCUZSEtBlPkRBlWxQ3ILNFkN6esB57K", "belamidemills29@gmail.com", "jet", "admin", "Donald Duck (Fake name)");
CALL create_account("gisadmin", "$2a$10$BdICfhUJOYP2w/IIhWu/MeTMJJCAkRby0rSUx6Vjm9fW/shFAmZ9C", "belamidemills29@gmail.com", "gis", "admin", "Micky Mouse (Fake name)");



CALL insert_message("text", "HELLO WORLD!", 1, 2);
CALL insert_message("text", "BUGS", 2, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "LATEST MESSAGE", 1, 2);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);
CALL insert_message("text", "ERRORS", 3, 1);





CALL insert_message("text", "1", 2, 1);
CALL insert_message("text", "2", 2, 1);
CALL insert_message("text", "3", 2, 1);
CALL insert_message("text", "4", 2, 1);
CALL insert_message("text", "5", 2, 1);
CALL insert_message("text", "6", 2, 1);
CALL insert_message("text", "7", 2, 1);
CALL insert_message("text", "8", 2, 1);
CALL insert_message("text", "9", 2, 1);
CALL insert_message("text", "10", 2, 1);
CALL insert_message("text", "11", 2, 1);
CALL insert_message("text", "12", 2, 1);
CALL insert_message("text", "13", 2, 1);
CALL insert_message("text", "14", 2, 1);
CALL insert_message("text", "15", 2, 1);
CALL insert_message("text", "16", 2, 1);
CALL insert_message("text", "17", 2, 1);
CALL insert_message("text", "18", 2, 1);
CALL insert_message("text", "19", 2, 1);
CALL insert_message("text", "20", 2, 1);
CALL insert_message("text", "21", 2, 1);
CALL insert_message("text", "22", 2, 1);
CALL insert_message("text", "23", 2, 1);
CALL insert_message("text", "24", 2, 1);
CALL insert_message("text", "25", 2, 1);
CALL insert_message("text", "26", 2, 1);
CALL insert_message("text", "27", 2, 1);
CALL insert_message("text", "28", 2, 1);
CALL insert_message("text", "29", 2, 1);
CALL insert_message("text", "30", 2, 1);
CALL insert_message("text", "31", 2, 1);
CALL insert_message("text", "32", 2, 1);
CALL insert_message("text", "33", 2, 1);
CALL insert_message("text", "34", 2, 1);
CALL insert_message("text", "35", 2, 1);
CALL insert_message("text", "36", 2, 1);
CALL insert_message("text", "37", 2, 1);
CALL insert_message("text", "38", 2, 1);
CALL insert_message("text", "39", 2, 1);
CALL insert_message("text", "40", 2, 1);
CALL insert_message("text", "41", 2, 1);
CALL insert_message("text", "42", 2, 1);
CALL insert_message("text", "43", 2, 1);
CALL insert_message("text", "44", 2, 1);
CALL insert_message("text", "45", 2, 1);
CALL insert_message("text", "46", 2, 1);
CALL insert_message("text", "47", 2, 1);
CALL insert_message("text", "48", 2, 1);
CALL insert_message("text", "49", 2, 1);
CALL insert_message("text", "50", 2, 1);
CALL insert_message("text", "51", 2, 1);
CALL insert_message("text", "52", 2, 1);
CALL insert_message("text", "53", 2, 1);
CALL insert_message("text", "54", 2, 1);
CALL insert_message("text", "55", 2, 1);
CALL insert_message("text", "56", 2, 1);
CALL insert_message("text", "57", 2, 1);
CALL insert_message("text", "58", 2, 1);
CALL insert_message("text", "59", 2, 1);
CALL insert_message("text", "60", 2, 1);
CALL insert_message("text", "61", 2, 1);
CALL insert_message("text", "62", 2, 1);
CALL insert_message("text", "63", 2, 1);
CALL insert_message("text", "64", 2, 1);
CALL insert_message("text", "65", 2, 1);
CALL insert_message("text", "66", 2, 1);
CALL insert_message("text", "67", 2, 1);
CALL insert_message("text", "68", 2, 1);
CALL insert_message("text", "69", 2, 1);
CALL insert_message("text", "70", 2, 1);
CALL insert_message("text", "71", 2, 1);
CALL insert_message("text", "72", 2, 1);
CALL insert_message("text", "73", 2, 1);
CALL insert_message("text", "74", 2, 1);
CALL insert_message("text", "75", 2, 1);
CALL insert_message("text", "76", 2, 1);
CALL insert_message("text", "77", 2, 1);
CALL insert_message("text", "78", 2, 1);
CALL insert_message("text", "79", 2, 1);
CALL insert_message("text", "80", 2, 1);
CALL insert_message("text", "81", 2, 1);
CALL insert_message("text", "82", 2, 1);
CALL insert_message("text", "83", 2, 1);
CALL insert_message("text", "84", 2, 1);
CALL insert_message("text", "85", 2, 1);
CALL insert_message("text", "86", 2, 1);
CALL insert_message("text", "87", 2, 1);
CALL insert_message("text", "88", 2, 1);
CALL insert_message("text", "89", 2, 1);
CALL insert_message("text", "90", 2, 1);
CALL insert_message("text", "91", 2, 1);
CALL insert_message("text", "92", 2, 1);
CALL insert_message("text", "93", 2, 1);
CALL insert_message("text", "94", 2, 1);
CALL insert_message("text", "95", 2, 1);
CALL insert_message("text", "96", 2, 1);
CALL insert_message("text", "97", 2, 1);
CALL insert_message("text", "98", 2, 1);
CALL insert_message("text", "99", 2, 1);
CALL insert_message("text", "100", 2, 1);
CALL insert_message("text", "101", 2, 1);
CALL insert_message("text", "102", 2, 1);
CALL insert_message("text", "103", 2, 1);
CALL insert_message("text", "104", 2, 1);
CALL insert_message("text", "105", 2, 1);
CALL insert_message("text", "106", 2, 1);
CALL insert_message("text", "107", 2, 1);
CALL insert_message("text", "108", 2, 1);
CALL insert_message("text", "109", 2, 1);
CALL insert_message("text", "110", 2, 1);
CALL insert_message("text", "111", 2, 1);
CALL insert_message("text", "112", 2, 1);
CALL insert_message("text", "113", 2, 1);
CALL insert_message("text", "114", 2, 1);
CALL insert_message("text", "115", 2, 1);
CALL insert_message("text", "116", 2, 1);
CALL insert_message("text", "117", 2, 1);
CALL insert_message("text", "118", 2, 1);
CALL insert_message("text", "119", 2, 1);
CALL insert_message("text", "120", 2, 1);
CALL insert_message("text", "121", 2, 1);
CALL insert_message("text", "122", 2, 1);
CALL insert_message("text", "123", 2, 1);
CALL insert_message("text", "124", 2, 1);
CALL insert_message("text", "125", 2, 1);
CALL insert_message("text", "126", 2, 1);
CALL insert_message("text", "127", 2, 1);
CALL insert_message("text", "128", 2, 1);
CALL insert_message("text", "129", 2, 1);
CALL insert_message("text", "130", 2, 1);
CALL insert_message("text", "131", 2, 1);
CALL insert_message("text", "132", 2, 1);
CALL insert_message("text", "133", 2, 1);
CALL insert_message("text", "134", 2, 1);
CALL insert_message("text", "135", 2, 1);
CALL insert_message("text", "136", 2, 1);
CALL insert_message("text", "137", 2, 1);
CALL insert_message("text", "138", 2, 1);
CALL insert_message("text", "139", 2, 1);
CALL insert_message("text", "140", 2, 1);
CALL insert_message("text", "141", 2, 1);
CALL insert_message("text", "142", 2, 1);
CALL insert_message("text", "143", 2, 1);
CALL insert_message("text", "144", 2, 1);
CALL insert_message("text", "145", 2, 1);
CALL insert_message("text", "146", 2, 1);
CALL insert_message("text", "147", 2, 1);
CALL insert_message("text", "148", 2, 1);
CALL insert_message("text", "149", 2, 1);
CALL insert_message("text", "150", 2, 1);
CALL insert_message("text", "151", 2, 1);
CALL insert_message("text", "152", 2, 1);
CALL insert_message("text", "153", 2, 1);
CALL insert_message("text", "154", 2, 1);
CALL insert_message("text", "155", 2, 1);
CALL insert_message("text", "156", 2, 1);
CALL insert_message("text", "157", 2, 1);
CALL insert_message("text", "158", 2, 1);
CALL insert_message("text", "159", 2, 1);
CALL insert_message("text", "160", 2, 1);
CALL insert_message("text", "161", 2, 1);
CALL insert_message("text", "162", 2, 1);
CALL insert_message("text", "163", 2, 1);
CALL insert_message("text", "164", 2, 1);
CALL insert_message("text", "165", 2, 1);
CALL insert_message("text", "166", 2, 1);
CALL insert_message("text", "167", 2, 1);
CALL insert_message("text", "168", 2, 1);
CALL insert_message("text", "169", 2, 1);
CALL insert_message("text", "170", 2, 1);
CALL insert_message("text", "171", 2, 1);
CALL insert_message("text", "172", 2, 1);
CALL insert_message("text", "173", 2, 1);
CALL insert_message("text", "174", 2, 1);
CALL insert_message("text", "175", 2, 1);
CALL insert_message("text", "176", 2, 1);
CALL insert_message("text", "177", 2, 1);
CALL insert_message("text", "178", 2, 1);
CALL insert_message("text", "179", 2, 1);
CALL insert_message("text", "180", 2, 1);
CALL insert_message("text", "181", 2, 1);
CALL insert_message("text", "182", 2, 1);
CALL insert_message("text", "183", 2, 1);
CALL insert_message("text", "184", 2, 1);
CALL insert_message("text", "185", 2, 1);
CALL insert_message("text", "186", 2, 1);
CALL insert_message("text", "187", 2, 1);
CALL insert_message("text", "188", 2, 1);
CALL insert_message("text", "189", 2, 1);
CALL insert_message("text", "190", 2, 1);
CALL insert_message("text", "191", 2, 1);
CALL insert_message("text", "192", 2, 1);
CALL insert_message("text", "193", 2, 1);
CALL insert_message("text", "194", 2, 1);
CALL insert_message("text", "195", 2, 1);
CALL insert_message("text", "196", 2, 1);
CALL insert_message("text", "197", 2, 1);
CALL insert_message("text", "198", 2, 1);
CALL insert_message("text", "199", 2, 1);
CALL insert_message("text", "200", 2, 1);



-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 10 SECOND), 1, 0, "2 MERRY CHRISTMAS!", "timoy", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 15 SECOND), 1, 0, "3 HAPPY NEW YEAR!", "bensoy", "timoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 20 SECOND), 1, 0, "4 PIT SENIOR!", "bensoy", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 25 SECOND), 1, 0, "5 GOOD MORNING!", "timoy", "bensoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 30 SECOND), 1, 0, "6 HAPPY HOLIDAYS!", "bensoy", "timoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 35 SECOND), 1, 0, "7 WELCOME BACK!", "timoy", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 40 SECOND), 1, 0, "8 CONGRATULATIONS!", "helsi", "bensoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 45 SECOND), 1, 0, "9 HAVE A GREAT DAY!", "bensoy", "timoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 50 SECOND), 1, 0, "10 GOOD NIGHT!", "helsi", "timoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 55 SECOND), 1, 0, "11 SEE YOU SOON!", "timoy", "bensoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 60 SECOND), 1, 0, "12 SAFE TRAVELS!", "bensoy", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 65 SECOND), 1, 0, "13 STAY STRONG!", "helsi", "timoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 70 SECOND), 1, 0, "14 THANK YOU!", "timoy", "bensoy");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 75 SECOND), 1, 0, "15 C", "helsi", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 80 SECOND), 1, 0, "16 C++", "helsi", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 85 SECOND), 1, 0, "17 C#", "helsi", "helsi");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 90 SECOND), 1, 0, "18 Java", "helsi", "helsi");

-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 90 SECOND), 1, 0, "HELLO WORLD!", "IBC admin", "Jet admin");
-- CALL insert_message(DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 90 SECOND), 1, 0, "HELLO LORD!", "Jet admin", "IBC admin");


-- CALL get_message("helsi", 1);
-- GETTING CONVERSATIONS HEAD
-- SELECT "CHAT HOME" AS _;
-- CALL get_conversations_heads("helsi");

-- -- GETTING CONVERSATION
-- SELECT "helsi & timoy" AS _;
-- CALL get_conversation("helsi", "timoy");

-- -- RELOCATING CONVERSATION TO LOGS
-- SELECT "relocating conversation to logs" AS _;
-- CALL relocate_conversation("timoy", "helsi");

-- -- GETTING LOGS TO SPECIFIC CONVERSATION
-- SELECT "conversation logs" AS _;
-- CALL get_conversation_logs(1);

-- -- GETTING ALL CONVERSATIONS HEAD LOGS
-- SELECT "conversation heads" AS _;
-- CALL get_conversations_heads_logs();

-- SELECT * FROM tbl_users;
-- SELECT * FROM tbl_messages;
-- SELECT * FROM tbl_messages_head;
-- SELECT * FROM tbl_messages_head_logs;
-- SELECT * FROM tbl_messages_logs;

-- SHOW PROCEDURE STATUS WHERE DB = DATABASE();